/* The Article Machine — data-history.js
   Modern Indian History: the timeline, the Acts, the people, the movements.

   HOW THIS DIFFERS FROM THE CONSTITUTION SUBJECT. The Constitution here is
   extracted from a government PDF — the text is the government's, verbatim.
   History has no equivalent single primary document, so this is written from
   the established historical record. Dates are where errors hide, so the ones
   sources most often disagree on were checked against sources before writing:
   the two dates of the Partition of Bengal, the founding of the two Home Rule
   Leagues, the Non-Cooperation timeline, the Communal Award and Poona Pact
   (including the 71-to-148 seat figure), and the Azad Hind government.

   Where historians genuinely disagree, the entry says so rather than picking
   a side quietly.                                                            */

window.HISTORY = {

eras: [
{id:"company",  n:"The Company's rise",              from:1600, to:1857,
 w:"A trading company acquires an empire — by treaty, by war, by annexation, and by the simple absence of anyone able to stop it."},
{id:"crown",    n:"Crown rule and early nationalism", from:1858, to:1904,
 w:"The Company is wound up, the Crown takes over, and an English-educated middle class begins to ask for representation."},
{id:"swadeshi", n:"Partition, Swadeshi and the split",from:1905, to:1914,
 w:"Curzon's partition of Bengal turns petitioning into agitation, and splits the Congress into Moderates and Extremists."},
{id:"gandhi",   n:"Gandhi's arrival to Chauri Chaura",from:1915, to:1922,
 w:"Satyagraha is tested in three local campaigns and then taken national. Jallianwala Bagh ends any hope of loyal reform."},
{id:"interwar", n:"Between the movements",            from:1923, to:1929,
 w:"Council entry, revolutionary action, Simon, the Nehru Report, and finally the demand for complete independence."},
{id:"civil",    n:"Civil Disobedience to the 1935 Act",from:1930,to:1939,
 w:"Salt, the Round Table Conferences, the Communal Award and the Poona Pact, and a constitution that becomes the template for 1950."},
{id:"endgame",  n:"War, Quit India and Partition",    from:1939, to:1947,
 w:"A war India was entered into without being asked, the last mass movement, the INA trials, and a partition negotiated in ten weeks."},
{id:"republic", n:"Independence and the Republic",     from:1947, to:1950,
 w:"The states brought in, the Mahatma killed, and a Constitution finished in the middle of both."}
],

/* ---------------------------------------------------------------- timeline */
timeline: [

/* ---- The Company's rise ---- */
{id:"charter-1600", y:1600, d:"31 December 1600", e:"company", t:"East India Company chartered",
 w:"Elizabeth I grants a monopoly on trade east of the Cape of Good Hope to a group of London merchants. The company that will govern India begins as a shareholding venture."},
{id:"surat-1613", y:1613, e:"company", t:"First English factory at Surat",
 w:"Jahangir permits a trading post. Thomas Roe arrives as James I's ambassador in 1615 and secures wider rights."},
{id:"madras-1639", y:1639, e:"company", t:"Madras founded",
 w:"Fort St George established — the first English territorial foothold. Bombay follows in 1668 (transferred from the Crown after Catherine of Braganza's dowry), Calcutta in 1690."},
{id:"plassey", y:1757, d:"23 June 1757", e:"company", t:"Battle of Plassey",
 w:"Robert Clive defeats Siraj-ud-Daula of Bengal, largely by buying Mir Jafar's defection. Militarily minor, politically decisive: the Company can now make and unmake a Nawab.", hy:1},
{id:"buxar", y:1764, d:"22 October 1764", e:"company", t:"Battle of Buxar",
 w:"The Company defeats the combined armies of Mir Qasim, Shuja-ud-Daula of Awadh and the Mughal emperor Shah Alam II. Unlike Plassey, this was a real victory over a real coalition — and it is what actually established British power in the east.", hy:1},
{id:"diwani", y:1765, e:"company", t:"Diwani of Bengal, Bihar and Odisha",
 w:"Shah Alam II grants the Company the right to collect revenue. Clive's 'dual government' follows: the Company takes the revenue, the Nawab keeps the responsibility for administration — and neither is accountable.", hy:1},
{id:"bengal-famine", y:1770, e:"company", t:"Great Bengal Famine",
 w:"Perhaps ten million dead, roughly a third of Bengal's population, while revenue collection continued. The scandal at home was one reason Parliament began to regulate the Company."},
{id:"regulating-act", y:1773, e:"company", t:"Regulating Act",
 w:"Parliament's first intervention. Warren Hastings becomes Governor-General of Bengal with a council of four; a Supreme Court is set up at Calcutta.", hy:1},
{id:"pitts", y:1784, e:"company", t:"Pitt's India Act",
 w:"Creates a Board of Control in London — the beginning of dual government between the Company and the Crown, which lasts until 1858.", hy:1},
{id:"third-mysore", y:1792, e:"company", t:"Treaty of Seringapatam",
 w:"Tipu Sultan cedes half his territory after the Third Anglo-Mysore War, and gives two sons as hostages."},
{id:"permanent-settlement", y:1793, e:"company", t:"Permanent Settlement of Bengal",
 w:"Cornwallis fixes land revenue in perpetuity and makes zamindars proprietors. It gave the Company a predictable income and created a landlord class whose abolition would take the first four amendments to the Constitution to secure.", hy:1},
{id:"charter-1793", y:1793, e:"company", t:"Charter Act 1793",
 w:"Renews the Company's monopoly for twenty years and puts the Governor-General's authority over the presidencies on a clear footing."},
{id:"subsidiary-alliance", y:1798, e:"company", t:"Wellesley's Subsidiary Alliance",
 w:"An Indian ruler accepts British troops, pays for them, surrenders foreign relations, and admits a British Resident. Hyderabad signs first. Conquest without the cost of conquest.", hy:1},
{id:"fourth-mysore", y:1799, d:"4 May 1799", e:"company", t:"Tipu Sultan killed at Seringapatam",
 w:"The Fourth Anglo-Mysore War ends the most formidable opposition in the south. Mysore is restored to the Wodeyars under subsidiary alliance."},
{id:"charter-1813", y:1813, e:"company", t:"Charter Act 1813",
 w:"Ends the Company's trade monopoly except for tea and the China trade, opens India to missionaries, and sets aside one lakh rupees a year for education — the first British commitment to educating Indians.", hy:1},
{id:"charter-1833", y:1833, e:"company", t:"Charter Act 1833",
 w:"Ends the Company's commercial functions entirely; it becomes a purely administrative body. Bentinck becomes Governor-General of India rather than of Bengal, and the Act declares that no Indian shall be disqualified from office by religion, birth, descent or colour.", hy:1},
{id:"sati", y:1829, e:"company", t:"Sati abolished",
 w:"Regulation XVII under Bentinck, following a long campaign by Raja Ram Mohan Roy. The first major social reform legislation, and the model for those that followed."},
{id:"macaulay", y:1835, e:"company", t:"Macaulay's Minute and English education",
 w:"Bentinck resolves that government funds will go to English-language education. Macaulay's aim, stated plainly, was 'a class of persons Indian in blood and colour, but English in taste, in opinions, in morals and in intellect'. That class produced the nationalist leadership.", hy:1},
{id:"charter-1853", y:1853, e:"company", t:"Charter Act 1853",
 w:"Separates the Governor-General's legislative and executive functions, and introduces open competition for the covered civil service — the beginning of the ICS examination.", hy:1},
{id:"railway", y:1853, e:"company", t:"First railway and telegraph",
 w:"Bombay to Thane, 34 km, April 1853; the Calcutta-Agra telegraph the same year. Built for troops, trade and control — and used, within a generation, to move newspapers and nationalists."},
{id:"woods", y:1854, e:"company", t:"Wood's Despatch",
 w:"Called the Magna Carta of English education in India: a graded school system, universities at Calcutta, Bombay and Madras (founded 1857), grants-in-aid and teacher training."},
{id:"doctrine-lapse", y:1848, e:"company", t:"Dalhousie's Doctrine of Lapse",
 w:"A princely state without a natural heir lapses to the Company; adopted heirs are not recognised. Satara, Jhansi, Nagpur and others annexed. Awadh was annexed in 1856 on a different ground — misgovernment — and both grievances fed 1857.", hy:1},
{id:"widow-remarriage", y:1856, e:"company", t:"Hindu Widows' Remarriage Act",
 w:"Legalised on Ishwar Chandra Vidyasagar's campaign."},

/* ---- 1857 ---- */
{id:"mangal-pandey", y:1857, d:"29 March 1857", e:"company", t:"Mangal Pandey at Barrackpore",
 w:"A sepoy of the 34th Native Infantry attacks his officers over the greased cartridges and is hanged on 8 April. The spark, though not yet the fire."},
{id:"revolt-1857", y:1857, d:"10 May 1857", e:"company", t:"The Revolt of 1857 begins at Meerut",
 w:"Sepoys mutiny, march on Delhi, and proclaim the aged Bahadur Shah Zafar emperor. It spread across the Gangetic plain and central India but not to Bengal, Punjab, Bombay or Madras, and the major princes stayed loyal. Called a mutiny by the British and the First War of Independence by Savarkar — the argument over what to call it is itself a stock question.", hy:1},
{id:"revolt-leaders", y:1857, e:"company", t:"The centres of the revolt",
 w:"Delhi under Bahadur Shah Zafar and Bakht Khan; Kanpur under Nana Saheb and Tantia Tope; Lucknow under Begum Hazrat Mahal; Jhansi under Rani Lakshmibai; Bareilly under Khan Bahadur Khan; Bihar under Kunwar Singh; Faizabad under Maulvi Ahmadullah Shah.", hy:1},

/* ---- Crown rule and early nationalism ---- */
{id:"queens-proclamation", y:1858, d:"1 November 1858", e:"crown", t:"Government of India Act and the Queen's Proclamation",
 w:"The Company is wound up. A Secretary of State for India in London, a Viceroy in India. Victoria's proclamation at Allahabad promises no further annexation, respect for treaties, and equal treatment of Indians in the services — a promise repeatedly cited by nationalists precisely because it was not kept.", hy:1},
{id:"indigo", y:1859, e:"crown", t:"Indigo Revolt in Bengal",
 w:"Ryots refuse to grow indigo for European planters. Dinabandhu Mitra's play Nil Darpan dramatised it; the Indigo Commission of 1860 followed."},
{id:"councils-1861", y:1861, e:"crown", t:"Indian Councils Act 1861",
 w:"Restores legislative power to Bombay and Madras and adds non-official Indian members to the Viceroy's council — nominated, not elected, and with no power over the budget. The beginning of Indian representation, and the beginning of complaints about it.", hy:1},
{id:"brahmo", y:1828, e:"company", t:"Brahmo Samaj founded",
 w:"Raja Ram Mohan Roy's reform society — against sati, caste, idolatry and polygamy; for widow remarriage, women's education and monotheism. Later led by Debendranath Tagore and Keshab Chandra Sen, and split more than once.", hy:1},
{id:"prarthana", y:1867, e:"crown", t:"Prarthana Samaj founded in Bombay",
 w:"Atmaram Pandurang, with M. G. Ranade and R. G. Bhandarkar. The western Indian counterpart of the Brahmo Samaj, more social than theological."},
{id:"arya-samaj", y:1875, e:"crown", t:"Arya Samaj founded",
 w:"Dayanand Saraswati, at Bombay. 'Back to the Vedas'; against idolatry, caste by birth and child marriage; the shuddhi movement for reconversion. His book: Satyarth Prakash.", hy:1},
{id:"theosophical", y:1875, e:"crown", t:"Theosophical Society founded",
 w:"Founded in New York by Madame Blavatsky and Colonel Olcott; headquarters moved to Adyar, Madras, in 1882. Annie Besant became president in 1907."},
{id:"aligarh", y:1875, e:"crown", t:"Sir Syed Ahmad Khan founds the Aligarh school",
 w:"The Muhammadan Anglo-Oriental College at Aligarh — modern education for Muslims, and the beginning of the Aligarh movement. It became a university in 1920."},
{id:"vernacular-press", y:1878, e:"crown", t:"Vernacular Press Act",
 w:"Lytton's law allowing the government to seize the press of any Indian-language newspaper it judged seditious — English-language papers exempt. Repealed by Ripon in 1882.", hy:1},
{id:"arms-act", y:1878, e:"crown", t:"Indian Arms Act",
 w:"Indians required a licence to keep arms; Europeans exempt. Another of Lytton's measures, and a standing grievance."},
{id:"ilbert", y:1883, e:"crown", t:"Ilbert Bill controversy",
 w:"Ripon's proposal to let Indian judges try Europeans provoked such organised European opposition that it was diluted. The episode taught Indian opinion two lessons: that the claim of equality before the law was hollow, and that organised agitation works.", hy:1},
{id:"inc-founded", y:1885, d:"28 December 1885", e:"crown", t:"Indian National Congress founded",
 w:"Seventy-two delegates meet at Gokuldas Tejpal Sanskrit College, Bombay. A. O. Hume, a retired ICS officer, was the moving spirit; W. C. Bonnerjee presided. Its early demands were representation, Indianisation of the services, and reduced military spending — put by petition.", hy:1},
{id:"drain", y:1901, e:"crown", t:"Dadabhai Naoroji publishes Poverty and Un-British Rule in India",
 w:"The drain of wealth theory, argued with figures: India's wealth was being transferred to Britain through home charges, salaries and pensions. It converted a moral complaint into an economic argument, and Naoroji became the first Indian in the British Parliament in 1892.", hy:1},
{id:"ramakrishna", y:1897, e:"crown", t:"Ramakrishna Mission founded",
 w:"Swami Vivekananda, after his address at the World's Parliament of Religions in Chicago in 1893. Emphasis on service as worship rather than on doctrinal reform."},
{id:"famine-commissions", y:1899, e:"crown", t:"Famines of 1896-97 and 1899-1900",
 w:"Millions dead under Curzon and his predecessor. The Famine Commissions that followed produced a code but not a policy of prevention, and the famines sharpened the economic critique of British rule."},

/* ---- Partition, Swadeshi and the split ---- */
{id:"universities-act", y:1904, e:"crown", t:"Indian Universities Act",
 w:"Curzon tightens government control over universities — attacked as an attempt to curb the nationalist middle class at its source."},
{id:"partition-bengal", y:1905, d:"announced 19 July, effective 16 October 1905", e:"swadeshi", t:"Partition of Bengal",
 w:"Curzon splits Bengal, creating Eastern Bengal and Assam with its capital at Dhaka. Presented as administrative convenience, understood as an attempt to divide Hindus and Muslims and break the centre of nationalist politics. Note the two dates — announced in July, effective in October.", hy:1},
{id:"swadeshi-movement", y:1905, e:"swadeshi", t:"Swadeshi and Boycott movement",
 w:"Boycott of British goods, promotion of Indian manufacture, national schools, samitis. It was the first movement to use economic pressure and mass symbolism, and it carried the Congress beyond petitioning.", hy:1},
{id:"muslim-league", y:1906, d:"30 December 1906", e:"swadeshi", t:"All India Muslim League founded at Dhaka",
 w:"Founded by Nawab Salimullah of Dhaka and others, initially loyalist in tone, seeking separate representation for Muslims.", hy:1},
{id:"calcutta-1906", y:1906, e:"swadeshi", t:"Calcutta session adopts Swaraj",
 w:"Dadabhai Naoroji, presiding, declares self-government within the Empire — swaraj — to be the Congress goal."},
{id:"surat-split", y:1907, e:"swadeshi", t:"Surat Split",
 w:"The Congress breaks between Moderates (Gokhale, Pherozeshah Mehta) and Extremists (Tilak, Lajpat Rai, Bipin Chandra Pal) over the presidency and over the pace and method of the movement. They reunite only at Lucknow in 1916.", hy:1},
{id:"morley-minto", y:1909, e:"swadeshi", t:"Indian Councils Act (Morley-Minto Reforms)",
 w:"Enlarged the legislative councils and admitted an elected element — and introduced separate electorates for Muslims, the single most consequential provision, since communal representation would run through every constitutional settlement until 1947.", hy:1},
{id:"delhi-durbar", y:1911, d:"12 December 1911", e:"swadeshi", t:"Delhi Durbar: partition annulled, capital moved",
 w:"George V announces the reversal of the partition of Bengal and the transfer of the capital from Calcutta to Delhi. Bihar and Odisha became a separate province the following year.", hy:1},
{id:"ghadar", y:1913, e:"swadeshi", t:"Ghadar Party founded",
 w:"Formed at San Francisco by Lala Har Dayal, Sohan Singh Bhakna and others among Indian emigrants, planning an armed rising. The 1915 attempt was betrayed and crushed."},
{id:"komagata", y:1914, e:"swadeshi", t:"Komagata Maru",
 w:"A ship carrying 376 Punjabi passengers is refused entry at Vancouver and forced back; on arrival at Budge Budge near Calcutta the police fire on them. A rallying point for the Ghadar movement."},

/* ---- Gandhi's arrival to Chauri Chaura ---- */
{id:"gandhi-returns", y:1915, d:"9 January 1915", e:"gandhi", t:"Gandhi returns from South Africa",
 w:"After twenty-one years and a satyagraha campaign already tested there. Gokhale, his political mentor, advised him to spend a year travelling India before speaking. 9 January is now observed as Pravasi Bharatiya Divas.", hy:1},
{id:"home-rule", y:1916, e:"gandhi", t:"The two Home Rule Leagues",
 w:"Tilak's Indian Home Rule League at Belgaum in April 1916, working in Maharashtra, Karnataka, Berar and the Central Provinces; Annie Besant's at Madras in September 1916, working in the rest of the country. Both demanded self-government within the Empire, and both put organisation into the countryside.", hy:1},
{id:"lucknow-pact", y:1916, e:"gandhi", t:"Lucknow Pact",
 w:"Congress and the Muslim League agree on a joint scheme of reforms — and the Congress accepts separate electorates. It is also the session at which the Moderates and Extremists reunite. Jinnah, then in both bodies, was its architect.", hy:1},
{id:"champaran", y:1917, e:"gandhi", t:"Champaran Satyagraha",
 w:"Gandhi's first satyagraha in India, against the tinkathia system that forced indigo cultivation on Bihar's peasants. He defied an order to leave, was prosecuted, and won an inquiry that ended the system.", hy:1},
{id:"kheda", y:1918, e:"gandhi", t:"Kheda Satyagraha",
 w:"A no-revenue campaign in Gujarat after crop failure. Gandhi's first peasant satyagraha over taxes, and Vallabhbhai Patel's entry into the movement.", hy:1},
{id:"ahmedabad", y:1918, e:"gandhi", t:"Ahmedabad Mill Strike",
 w:"Gandhi's first hunger strike, in support of textile workers seeking a wage increase. The dispute went to arbitration and the workers got 35 per cent.", hy:1},
{id:"montford", y:1918, e:"gandhi", t:"Montagu-Chelmsford Report",
 w:"Follows Montagu's August 1917 declaration of 'increasing association of Indians in every branch of the administration' and 'responsible government' as the goal. The report becomes the Government of India Act 1919."},
{id:"rowlatt", y:1919, d:"March 1919", e:"gandhi", t:"Rowlatt Act",
 w:"Detention without trial and trial without jury, extending wartime emergency powers into peacetime. 'No appeal, no vakil, no daleel.' Gandhi called a nationwide hartal for 6 April — his first all-India campaign.", hy:1},
{id:"jallianwala", y:1919, d:"13 April 1919", e:"gandhi", t:"Jallianwala Bagh massacre",
 w:"General Dyer orders firing on an enclosed, unarmed gathering at Amritsar without warning, and continues until the ammunition runs low. Official figure 379 dead; Indian estimates far higher. Tagore renounced his knighthood. It ended, for a generation, the belief that British rule could be reformed from within.", hy:1},
{id:"goi-1919", y:1919, e:"gandhi", t:"Government of India Act 1919",
 w:"Introduces dyarchy in the provinces: 'transferred' subjects such as education and health to Indian ministers, 'reserved' subjects such as police and finance to the Governor. A bicameral central legislature, and separate electorates extended to Sikhs, Christians, Anglo-Indians and Europeans.", hy:1},
{id:"khilafat", y:1919, e:"gandhi", t:"Khilafat movement",
 w:"Indian Muslims organise against the dismemberment of the Ottoman Caliphate after the war, led by the Ali brothers, Maulana Azad and Hasrat Mohani. Gandhi joined it to the national movement — the high point of Hindu-Muslim political unity, and it collapsed when Ataturk abolished the Caliphate in 1924.", hy:1},
{id:"non-cooperation", y:1920, d:"launched 1 August 1920", e:"gandhi", t:"Non-Cooperation Movement",
 w:"Surrender of titles, boycott of councils, courts, schools and foreign cloth; national institutions founded in their place. Approved at the Calcutta special session in September 1920 and endorsed at Nagpur in December. The first genuinely mass movement.", hy:1},
{id:"nagpur-1920", y:1920, e:"gandhi", t:"Nagpur session reorganises the Congress",
 w:"Provincial committees on linguistic lines, a working committee, a four-anna membership. The Congress stops being a once-a-year gathering of lawyers and becomes a machine."},
{id:"moplah", y:1921, e:"gandhi", t:"Moplah rebellion in Malabar",
 w:"A tenant rising against landlords that acquired a communal character, and which the Congress leadership found impossible to defend or disown."},
{id:"chauri-chaura", y:1922, d:"5 February 1922", e:"gandhi", t:"Chauri Chaura, and the withdrawal",
 w:"A procession burns a police station in Gorakhpur district, killing twenty-two policemen. Gandhi withdrew the movement on 11 February — to the fury of Nehru, Bose and others who were in jail and thought the moment was being thrown away. It is the central argument about Gandhi's leadership.", hy:1},

/* ---- Between the movements ---- */
{id:"swaraj-party", y:1923, e:"interwar", t:"Swaraj Party founded",
 w:"C. R. Das and Motilal Nehru break with the no-changers to contest the council elections and obstruct from within. They won substantial seats and defeated government bills, but the strategy faded after Das died in 1925.", hy:1},
{id:"hsra", y:1924, e:"interwar", t:"Hindustan Republican Association",
 w:"Founded by Sachindranath Sanyal and Ramprasad Bismil; reorganised in 1928 as the Hindustan Socialist Republican Association with Bhagat Singh, Chandrashekhar Azad and Sukhdev."},
{id:"kakori", y:1925, d:"9 August 1925", e:"interwar", t:"Kakori conspiracy",
 w:"HRA revolutionaries rob a train carrying government money near Lucknow. Ramprasad Bismil, Ashfaqullah Khan, Roshan Singh and Rajendra Lahiri were hanged."},
{id:"simon", y:1927, e:"interwar", t:"Simon Commission appointed",
 w:"A statutory commission to review the 1919 Act with seven members and not one Indian. Boycotted by almost every party. It landed at Bombay on 3 February 1928 to black flags and 'Simon Go Back'; Lala Lajpat Rai was injured in a lathi charge at Lahore and died weeks later.", hy:1},
{id:"nehru-report", y:1928, e:"interwar", t:"Nehru Report",
 w:"An all-party answer to the challenge to produce a constitution. Motilal Nehru's committee proposed dominion status, joint electorates with reserved seats, and fundamental rights — and it was rejected by Jinnah, who replied with his Fourteen Points in 1929.", hy:1},
{id:"bardoli", y:1928, e:"interwar", t:"Bardoli Satyagraha",
 w:"A no-tax campaign against a thirty per cent revenue increase, led by Vallabhbhai Patel. Its success won him the title Sardar, conferred by the women of Bardoli."},
{id:"assembly-bomb", y:1929, d:"8 April 1929", e:"interwar", t:"Bhagat Singh and Batukeshwar Dutt bomb the Central Legislative Assembly",
 w:"A deliberately harmless bomb, thrown 'to make the deaf hear', followed by a refusal to escape. The trial gave them a platform; Bhagat Singh, Sukhdev and Rajguru were hanged on 23 March 1931 for the killing of Saunders.", hy:1},
{id:"lahore-1929", y:1929, d:"December 1929", e:"interwar", t:"Lahore session: Purna Swaraj",
 w:"Under Jawaharlal Nehru's presidency the Congress adopts complete independence as its goal and authorises civil disobedience. The tricolour was hoisted on the banks of the Ravi.", hy:1},
{id:"first-independence-day", y:1930, d:"26 January 1930", e:"civil", t:"First Independence Day observed",
 w:"The Congress asks Indians to pledge independence on this day. Twenty years later the same date was chosen for the Constitution to come into force — which is why India's Republic Day is 26 January.", hy:1},

/* ---- Civil Disobedience to the 1935 Act ---- */
{id:"dandi", y:1930, d:"12 March to 6 April 1930", e:"civil", t:"Dandi March and the Salt Satyagraha",
 w:"Gandhi walks 240 miles from Sabarmati to Dandi with 78 followers and makes salt from seawater, breaking the salt monopoly. Salt was chosen because everyone used it and everyone was taxed on it. The movement spread far beyond salt — to forest laws, revenue refusal and boycott.", hy:1},
{id:"rtc1", y:1930, d:"November 1930", e:"civil", t:"First Round Table Conference",
 w:"Held in London without the Congress, which was boycotting. Ambedkar attended, as did the princes and the League."},
{id:"gandhi-irwin", y:1931, d:"5 March 1931", e:"civil", t:"Gandhi-Irwin Pact",
 w:"Civil disobedience suspended, political prisoners released, salt-making allowed for personal use on the coast — in exchange for Congress participation in the Second Round Table Conference.", hy:1},
{id:"rtc2", y:1931, d:"September 1931", e:"civil", t:"Second Round Table Conference",
 w:"Gandhi attends as the Congress's sole representative and it fails, chiefly on the question of separate electorates for the depressed classes, which Ambedkar pressed and Gandhi resisted.", hy:1},
{id:"communal-award", y:1932, d:"16 August 1932", e:"civil", t:"Communal Award",
 w:"Ramsay MacDonald grants separate electorates to the depressed classes as well as to Muslims, Sikhs, Europeans, Anglo-Indians and Indian Christians — 71 seats reserved. Gandhi began a fast unto death in Yerwada jail against the separate electorate for the depressed classes alone.", hy:1},
{id:"poona-pact", y:1932, d:"24 September 1932", e:"civil", t:"Poona Pact",
 w:"Ambedkar gives up separate electorates in exchange for far more reserved seats within a joint electorate: 148 in the provincial legislatures rather than 71, and 18 per cent of the general seats in the central legislature. Both men gave something up, and both understood it differently ever afterwards.", hy:1},
{id:"rtc3", y:1932, d:"November 1932", e:"civil", t:"Third Round Table Conference",
 w:"Neither the Congress nor the Labour opposition attended. Its work fed the White Paper that became the 1935 Act."},
{id:"goi-1935", y:1935, e:"civil", t:"Government of India Act 1935",
 w:"The longest Act the British Parliament had then passed. An All-India Federation (never established, because the princes would not join), provincial autonomy replacing dyarchy, dyarchy moved to the centre, a Federal Court, and the RBI. Its administrative structure is the direct ancestor of the Constitution of 1950 — a great deal of the 1950 text is lifted from it.", hy:1},
{id:"provincial-1937", y:1937, e:"civil", t:"Provincial elections and Congress ministries",
 w:"The Congress wins majorities in most provinces and forms ministries in eight. The League fares badly, and the experience of Congress rule between 1937 and 1939 hardened its case that Muslims needed a separate settlement.", hy:1},
{id:"forward-bloc", y:1939, e:"civil", t:"Bose resigns and founds the Forward Bloc",
 w:"Subhas Chandra Bose defeats Gandhi's candidate Pattabhi Sitaramayya at the Tripuri session in 1939, then resigns as Congress president under pressure and forms the Forward Bloc.", hy:1},

/* ---- War, Quit India and Partition ---- */
{id:"war-declared", y:1939, e:"endgame", t:"India declared at war without consultation",
 w:"Linlithgow commits India to the war without asking the legislature or the provincial governments. The Congress ministries resign in protest; the League observed the day as Deliverance Day.", hy:1},
{id:"lahore-resolution", y:1940, d:"23 March 1940", e:"endgame", t:"Lahore Resolution",
 w:"The Muslim League resolves for 'independent states' in the Muslim-majority north-west and east. It does not use the word Pakistan — that came from the press — and it says states, plural. It is the formal beginning of the demand.", hy:1},
{id:"august-offer", y:1940, e:"endgame", t:"August Offer",
 w:"Dominion status as the long-term goal, an expanded executive council, and a war advisory council. Rejected by the Congress; the League welcomed the assurance that no settlement would be imposed on unwilling minorities."},
{id:"individual-satyagraha", y:1940, e:"endgame", t:"Individual Satyagraha",
 w:"A symbolic anti-war campaign, deliberately individual rather than mass. Vinoba Bhave was the first satyagrahi, Nehru the second."},
{id:"cripps", y:1942, d:"March 1942", e:"endgame", t:"Cripps Mission",
 w:"Offers dominion status after the war and a constituent assembly, with a right for provinces to stay out. Rejected: Gandhi called it 'a post-dated cheque'. The right to opt out conceded the principle of partition.", hy:1},
{id:"quit-india", y:1942, d:"8 August 1942", e:"endgame", t:"Quit India Movement",
 w:"The Congress passes the Quit India resolution at Bombay; Gandhi's call is 'Do or Die'. The entire leadership was arrested within hours, and the movement ran without them — strikes, sabotage, parallel governments at Ballia, Tamluk and Satara. The most spontaneous of the mass movements, and the most severely repressed.", hy:1},
{id:"azad-hind", y:1943, d:"21 October 1943", e:"endgame", t:"Provisional Government of Azad Hind",
 w:"Bose proclaims a provisional government of free India at Singapore and declares war on Britain and the United States. The INA fought at Imphal and Kohima in 1944. Bose's slogans — 'Give me blood and I will give you freedom', 'Jai Hind' — outlived the campaign.", hy:1},
{id:"bengal-famine-43", y:1943, e:"endgame", t:"Bengal famine",
 w:"Between two and three million dead. Wartime procurement, the denial policy on boats and rice in coastal Bengal, and a refusal to divert shipping turned a shortage into a catastrophe."},
{id:"wavell", y:1945, e:"endgame", t:"Wavell Plan and the Simla Conference",
 w:"An offer to reconstitute the executive council with equal Caste Hindu and Muslim representation. It broke down on Jinnah's insistence that the League alone could nominate Muslim members."},
{id:"ina-trials", y:1945, e:"endgame", t:"INA trials at the Red Fort",
 w:"The public trial of Shah Nawaz Khan, Prem Sahgal and Gurbaksh Singh Dhillon — deliberately one Muslim, one Hindu and one Sikh — produced exactly the wrong effect: nationwide sympathy, defence by Bhulabhai Desai and Nehru, and unrest in the armed forces.", hy:1},
{id:"naval-mutiny", y:1946, d:"February 1946", e:"endgame", t:"Royal Indian Navy mutiny",
 w:"Ratings at Bombay strike over food and racial discrimination; it spreads to Karachi and Calcutta and draws civilian support. More than any single event it convinced the British that the loyalty of Indian forces could no longer be assumed.", hy:1},
{id:"cabinet-mission", y:1946, d:"March 1946", e:"endgame", t:"Cabinet Mission",
 w:"Rejected Pakistan and proposed instead a three-tier federation: provinces, groups of provinces, and a weak centre handling defence, foreign affairs and communications — plus a constituent assembly. Both parties accepted and then interpreted the grouping clause differently, and it collapsed.", hy:1},
{id:"direct-action", y:1946, d:"16 August 1946", e:"endgame", t:"Direct Action Day",
 w:"The League calls a day of direct action to press for Pakistan. Calcutta erupts; several thousand die in four days, and the killing spread to Noakhali, Bihar and the Punjab. After this the argument for a united India was being made over communal violence."},
{id:"interim-govt", y:1946, d:"2 September 1946", e:"endgame", t:"Interim Government formed",
 w:"Nehru as Vice-President of the Viceroy's Executive Council. The League joined in October, having initially refused, and used its position to obstruct."},
{id:"constituent-assembly", y:1946, d:"9 December 1946", e:"endgame", t:"Constituent Assembly first meets",
 w:"Sachchidananda Sinha as temporary chairman; Rajendra Prasad elected president on 11 December. The League stayed away. Nehru moved the Objectives Resolution on 13 December 1946, and it became the Preamble.", hy:1},
{id:"mountbatten-plan", y:1947, d:"3 June 1947", e:"endgame", t:"Mountbatten Plan",
 w:"Partition, with the provincial legislatures of Bengal and Punjab to vote on dividing their provinces, a referendum in the North-West Frontier Province and Sylhet, and dominion status for both new states. The date for transfer was advanced from June 1948 to August 1947.", hy:1},
{id:"independence-act", y:1947, d:"18 July 1947", e:"endgame", t:"Indian Independence Act",
 w:"Two independent dominions from 15 August 1947, each with a constituent assembly holding full legislative power, and the lapse of British paramountcy over the princely states. Article 395 of the Constitution repeals this Act — the cord is formally cut in 1950.", hy:1},
{id:"radcliffe", y:1947, e:"endgame", t:"The Radcliffe Line",
 w:"Cyril Radcliffe, who had never been to India, was given five weeks to draw the boundary through Punjab and Bengal. The awards were published on 17 August, two days after independence. Between ten and twenty million people moved; estimates of the dead run from several hundred thousand to a million.", hy:1},
{id:"independence", y:1947, d:"15 August 1947", e:"endgame", t:"Independence",
 w:"Nehru's 'Tryst with Destiny' speech to the Constituent Assembly at midnight. Gandhi was not in Delhi; he was in Calcutta, fasting against the communal killing.", hy:1},
{id:"integration", y:1948, e:"republic", t:"Integration of the princely states",
 w:"Patel and V. P. Menon secure the accession of 562 states, almost all by 15 August 1947, on an instrument covering defence, external affairs and communications. Three were exceptions and each was settled differently: Junagadh by plebiscite, Hyderabad by police action in September 1948, and Jammu and Kashmir by an instrument of accession in October 1947 after a tribal invasion.", hy:1},
{id:"gandhi-assassination", y:1948, d:"30 January 1948", e:"republic", t:"Gandhi assassinated",
 w:"Shot at Birla House, New Delhi, by Nathuram Godse."},
{id:"constitution-adopted", y:1949, d:"26 November 1949", e:"republic", t:"Constitution adopted",
 w:"The Constituent Assembly adopts the Constitution after 2 years, 11 months and 18 days. It came into force on 26 January 1950 — the date chosen for the Purna Swaraj pledge of 1930.", hy:1}
],

/* -------------------------------------------------------------------- acts */
acts: [
{id:"a-1773", y:1773, n:"Regulating Act",
 w:"Parliament's first attempt to control the Company after the Bengal famine and the Company's near-bankruptcy.",
 k:["Governor of Bengal becomes Governor-General of Bengal — Warren Hastings the first",
    "An executive council of four, deciding by majority, with the Governor-General having only a casting vote",
    "Bombay and Madras subordinated to Bengal",
    "A Supreme Court at Calcutta (1774)",
    "Company servants forbidden private trade and presents"]},
{id:"a-1784", y:1784, n:"Pitt's India Act",
 w:"Established dual government — the Company traded, the Crown governed — which lasted until 1858.",
 k:["Board of Control created in London over civil, military and revenue affairs",
    "Court of Directors kept commercial functions",
    "The Company's territories called 'British possessions in India' for the first time",
    "Governor-General's council reduced to three"]},
{id:"a-1793", y:1793, n:"Charter Act 1793",
 w:"Renewed the monopoly and tidied the machinery.",
 k:["Company's trade monopoly extended twenty years",
    "Governor-General given power to override his council",
    "Company servants paid out of Indian revenues",
    "Royal approval required for the Governor-General, Governors and Commander-in-Chief"]},
{id:"a-1813", y:1813, n:"Charter Act 1813",
 w:"The first breach in the monopoly, and the first money for education.",
 k:["Trade monopoly ended except for tea and the trade with China",
    "Missionaries permitted to enter India",
    "One lakh rupees a year for the revival of literature and the promotion of science among Indians",
    "Company's rule extended twenty years"]},
{id:"a-1833", y:1833, n:"Charter Act 1833",
 w:"The Company stops trading and becomes purely an administrator.",
 k:["Governor-General of Bengal becomes Governor-General of India — Lord William Bentinck the first",
    "All commercial activities of the Company ended",
    "Bombay and Madras stripped of legislative power",
    "A Law Member added to the council — Macaulay, who chaired the first Law Commission",
    "No Indian to be disqualified from office by religion, place of birth, descent or colour"]},
{id:"a-1853", y:1853, n:"Charter Act 1853",
 w:"The last of the Charter Acts, and the one that created the competitive civil service.",
 k:["Legislative and executive functions of the Governor-General's council separated",
    "Open competition for the covered civil service; the Macaulay Committee followed in 1854",
    "Local representation added to the legislative council",
    "The Company's rule extended without a fixed term — an admission that it would not last"]},
{id:"a-1858", y:1858, n:"Government of India Act 1858",
 w:"The Company is abolished and the Crown takes over. Passed in the aftermath of 1857.",
 k:["Rule transferred from the Company to the Crown",
    "Secretary of State for India created, a member of the British Cabinet, with a Council of India of fifteen",
    "Governor-General also styled Viceroy — Canning the first",
    "Board of Control and Court of Directors abolished"]},
{id:"a-1861", y:1861, n:"Indian Councils Act 1861",
 w:"The beginning of Indian representation, and of the complaint that it was not representation at all.",
 k:["Non-official Indian members nominated to the Viceroy's legislative council",
    "Legislative power restored to Bombay and Madras — the start of decentralisation",
    "The portfolio system recognised",
    "The Viceroy given power to issue ordinances in an emergency"]},
{id:"a-1892", y:1892, n:"Indian Councils Act 1892",
 w:"An indirect, limited and unnamed step towards election.",
 k:["Council membership increased; non-officials still in a minority",
    "Nomination on the recommendation of local bodies and chambers of commerce — election in substance, not in name",
    "Members allowed to discuss the budget and put questions, but not to vote or supplement"]},
{id:"a-1909", y:1909, n:"Indian Councils Act 1909 (Morley-Minto)",
 w:"Introduced separate electorates — the provision that shaped everything that followed.",
 k:["Legislative councils enlarged at the centre and in the provinces",
    "Separate electorates for Muslims: only Muslims voting for Muslim seats",
    "An Indian admitted to the Viceroy's executive council — S. P. Sinha as Law Member",
    "Members allowed to move resolutions and ask supplementary questions"]},
{id:"a-1919", y:1919, n:"Government of India Act 1919 (Montagu-Chelmsford)",
 w:"Dyarchy: responsibility handed over in the provinces, but only for the subjects that mattered least.",
 k:["Provincial subjects split into 'transferred' (Indian ministers) and 'reserved' (the Governor)",
    "Central and provincial subjects separated; provincial budgets divided",
    "Bicameral central legislature — Council of State and Legislative Assembly",
    "Separate electorates extended to Sikhs, Indian Christians, Anglo-Indians and Europeans",
    "A Public Service Commission provided for (set up 1926); a statutory commission after ten years — which became Simon"]},
{id:"a-1935", y:1935, n:"Government of India Act 1935",
 w:"The template for 1950. Much of the Constitution's administrative structure comes straight from it.",
 k:["An All-India Federation of provinces and princely states — never established, as the princes did not accede",
    "Provincial autonomy: dyarchy abolished in the provinces, ministers responsible to the legislature",
    "Dyarchy introduced at the centre instead",
    "Three lists — Federal, Provincial and Concurrent — the direct ancestor of the Seventh Schedule",
    "Federal Court established (1937), and the Reserve Bank of India",
    "Separate electorates extended to depressed classes, women and labour",
    "Burma separated from India"]},
{id:"a-1947", y:1947, n:"Indian Independence Act 1947",
 w:"The Act that ended the Raj — and that article 395 of the Constitution repeals.",
 k:["Two independent dominions, India and Pakistan, from 15 August 1947",
    "Each constituent assembly given full power to frame a constitution, and to repeal any Act of the British Parliament",
    "The office of Secretary of State for India abolished",
    "British paramountcy over the princely states lapsed, leaving them free to accede to either dominion",
    "Until a new constitution, each dominion governed under the 1935 Act as adapted"]}
],

/* ------------------------------------------------------------------ people */
people: [
{id:"rammohan", n:"Raja Ram Mohan Roy", y:"1772–1833", r:"Reformer",
 w:"Founded the Brahmo Samaj (1828) and campaigned against sati, which Bentinck abolished in 1829. Called the father of the Indian Renaissance. Published Sambad Kaumudi and Mirat-ul-Akhbar; the title Raja was given by the Mughal emperor Akbar II, whose case he took to London.", hy:1},
{id:"vidyasagar", n:"Ishwar Chandra Vidyasagar", y:"1820–1891", r:"Reformer, educationist",
 w:"Drove the Hindu Widows' Remarriage Act, 1856, and campaigned against child marriage and polygamy. Principal of Sanskrit College, which he opened to non-Brahmins.", hy:1},
{id:"dayanand", n:"Dayanand Saraswati", y:"1824–1883", r:"Founder of the Arya Samaj",
 w:"'Back to the Vedas.' Founded the Arya Samaj in 1875; wrote Satyarth Prakash; started the shuddhi movement. Also among the first to use the word swaraj.", hy:1},
{id:"vivekananda", n:"Swami Vivekananda", y:"1863–1902", r:"Monk, founder of the Ramakrishna Mission",
 w:"Disciple of Ramakrishna Paramhansa. His 1893 address at the World's Parliament of Religions in Chicago made him internationally known; founded the Ramakrishna Mission in 1897, with service as its creed.", hy:1},
{id:"syed-ahmad", n:"Sir Syed Ahmad Khan", y:"1817–1898", r:"Educationist",
 w:"Founded the Muhammadan Anglo-Oriental College at Aligarh in 1875 and the Aligarh movement — modern education for Muslims, and political loyalism. Wrote The Causes of the Indian Revolt.", hy:1},
{id:"phule", n:"Jyotirao Phule", y:"1827–1890", r:"Social reformer",
 w:"Founded the Satyashodhak Samaj (1873) against caste and Brahmin dominance; opened schools for girls and for the depressed classes with Savitribai Phule. Wrote Gulamgiri.", hy:1},
{id:"periyar", n:"E. V. Ramasamy 'Periyar'", y:"1879–1973", r:"Self-Respect Movement",
 w:"Founded the Self-Respect Movement (1925) and the Dravidar Kazhagam; campaigned against caste, Brahmin dominance and the imposition of Hindi."},
{id:"naoroji", n:"Dadabhai Naoroji", y:"1825–1917", r:"The Grand Old Man of India",
 w:"Author of the drain of wealth theory in Poverty and Un-British Rule in India (1901). First Indian elected to the British House of Commons, 1892. Congress president three times, and at Calcutta in 1906 declared swaraj the goal.", hy:1},
{id:"gokhale", n:"Gopal Krishna Gokhale", y:"1866–1915", r:"Moderate leader",
 w:"Founded the Servants of India Society (1905). Gandhi's political mentor, who told him to spend a year travelling India before speaking on politics.", hy:1},
{id:"tilak", n:"Bal Gangadhar Tilak", y:"1856–1920", r:"Extremist leader",
 w:"'Swaraj is my birthright and I shall have it.' Founded Kesari and Maratha; used the Ganapati and Shivaji festivals for mass mobilisation; imprisoned in Mandalay 1908-14, where he wrote Gita Rahasya. Founded the Indian Home Rule League in April 1916 at Belgaum.", hy:1},
{id:"lajpat", n:"Lala Lajpat Rai", y:"1865–1928", r:"Extremist leader",
 w:"The Punjab Kesari, and one of Lal-Bal-Pal. Injured in a lathi charge while protesting the Simon Commission at Lahore and died weeks later — the death that Bhagat Singh and his associates set out to avenge.", hy:1},
{id:"bipin-pal", n:"Bipin Chandra Pal", y:"1858–1932", r:"Extremist leader",
 w:"The third of Lal-Bal-Pal, and a leading voice of Swadeshi and boycott."},
{id:"aurobindo", n:"Aurobindo Ghosh", y:"1872–1950", r:"Revolutionary, then philosopher",
 w:"Wrote in Bande Mataram; tried in the Alipore bomb case of 1908 and defended by C. R. Das; withdrew to Pondicherry in 1910 and left politics entirely."},
{id:"annie-besant", n:"Annie Besant", y:"1847–1933", r:"Theosophist, Home Rule leader",
 w:"President of the Theosophical Society from 1907; founded her Home Rule League at Madras in September 1916; interned in 1917 and then elected the first woman president of the Congress at Calcutta the same year.", hy:1},
{id:"gandhi", n:"Mohandas Karamchand Gandhi", y:"1869–1948", r:"Leader of the national movement",
 w:"Returned from South Africa in January 1915. Champaran, Kheda and Ahmedabad in 1917-18; Non-Cooperation from 1920; Salt Satyagraha in 1930; Quit India in 1942. Assassinated on 30 January 1948. Titles: Mahatma from Tagore, Bapu, and Father of the Nation.", hy:1},
{id:"nehru", n:"Jawaharlal Nehru", y:"1889–1964", r:"First Prime Minister",
 w:"Congress president at Lahore in 1929, where Purna Swaraj was adopted; moved the Objectives Resolution in December 1946; Vice-President of the Interim Government from September 1946; Prime Minister from 15 August 1947. Wrote The Discovery of India in Ahmadnagar Fort.", hy:1},
{id:"patel", n:"Vallabhbhai Patel", y:"1875–1950", r:"The Iron Man, Sardar",
 w:"Led the Kheda and Bardoli satyagrahas — Bardoli won him the title Sardar. As Deputy Prime Minister and Home Minister he and V. P. Menon integrated 562 princely states. Chaired the Constituent Assembly committees on fundamental rights and minorities.", hy:1},
{id:"ambedkar", n:"B. R. Ambedkar", y:"1891–1956", r:"Chairman of the Drafting Committee",
 w:"Led the depressed classes at the Round Table Conferences; signed the Poona Pact in 1932; founded the Independent Labour Party and later the Scheduled Castes Federation. Chairman of the Drafting Committee and first Law Minister. Wrote Annihilation of Caste. Converted to Buddhism in 1956.", hy:1},
{id:"bose", n:"Subhas Chandra Bose", y:"1897–1945",  r:"Netaji",
 w:"Congress president 1938 and 1939; resigned after Tripuri and founded the Forward Bloc. Escaped India in 1941, reached Germany and then south-east Asia; took command of the Indian National Army and proclaimed the Provisional Government of Azad Hind at Singapore on 21 October 1943.", hy:1},
{id:"bhagat-singh", n:"Bhagat Singh", y:"1907–1931", r:"Revolutionary",
 w:"HSRA. Killed Saunders in 1928 in revenge for Lajpat Rai; threw a bomb in the Central Legislative Assembly with B. K. Dutt on 8 April 1929 and courted arrest. Wrote Why I Am an Atheist. Hanged with Sukhdev and Rajguru on 23 March 1931.", hy:1},
{id:"azad", n:"Chandrashekhar Azad", y:"1906–1931", r:"Revolutionary",
 w:"Reorganised the HRA into the HSRA. Shot himself at Alfred Park, Allahabad, in February 1931 rather than be taken."},
{id:"maulana-azad", n:"Maulana Abul Kalam Azad", y:"1888–1958", r:"Congress president, first Education Minister",
 w:"Youngest Congress president in 1923 and president through the crucial years 1940-46. Edited Al-Hilal and Al-Balagh. Opposed partition to the end. Wrote India Wins Freedom."},
{id:"jinnah", n:"Muhammad Ali Jinnah", y:"1876–1948", r:"Leader of the Muslim League",
 w:"Architect of the Lucknow Pact of 1916 and once called the ambassador of Hindu-Muslim unity; left the Congress after Non-Cooperation; issued the Fourteen Points in 1929; moved the Lahore Resolution in 1940; called Direct Action Day in 1946; first Governor-General of Pakistan.", hy:1},
{id:"rajendra-prasad", n:"Rajendra Prasad", y:"1884–1963", r:"President of the Constituent Assembly",
 w:"Led the Champaran inquiry with Gandhi; president of the Constituent Assembly from 11 December 1946; first President of India, and the only one to serve two full terms."},
{id:"rajaji", n:"C. Rajagopalachari", y:"1878–1972", r:"Last Governor-General",
 w:"The only Indian and last Governor-General of India, 1948-50. Proposed the CR Formula in 1944 as a basis for settlement with the League. Later founded the Swatantra Party."},
{id:"sarojini", n:"Sarojini Naidu", y:"1879–1949", r:"The Nightingale of India",
 w:"First Indian woman president of the Congress, at Kanpur in 1925; led the raid on the Dharasana salt works in 1930 after Gandhi's arrest; first woman Governor of a State, United Provinces."},
{id:"tagore", n:"Rabindranath Tagore", y:"1861–1941", r:"Poet",
 w:"First non-European Nobel laureate in Literature, 1913, for Gitanjali. Renounced his knighthood after Jallianwala Bagh. Wrote Jana Gana Mana and Amar Shonar Bangla, the national anthems of India and Bangladesh; gave Gandhi the title Mahatma.", hy:1},
{id:"vp-menon", n:"V. P. Menon", y:"1893–1966", r:"Civil servant",
 w:"Drafted the plan for partition and dominion status that Mountbatten adopted, and worked with Patel on the integration of the princely states."},
{id:"curzon", n:"Lord Curzon", y:"Viceroy 1899–1905", r:"Viceroy",
 w:"Partitioned Bengal in 1905, passed the Indian Universities Act of 1904 and the Ancient Monuments Preservation Act, and created the North-West Frontier Province. No Viceroy did more to create the movement he despised.", hy:1},
{id:"dalhousie", n:"Lord Dalhousie", y:"Governor-General 1848–1856", r:"Governor-General",
 w:"Doctrine of Lapse; annexation of Awadh in 1856; first railway, telegraph and postage stamp; the Public Works Department; Wood's Despatch of 1854.", hy:1},
{id:"ripon", n:"Lord Ripon", y:"Viceroy 1880–1884", r:"Viceroy",
 w:"Repealed the Vernacular Press Act; the Ilbert Bill; the resolution of 1882 on local self-government, which is why he is called the father of local self-government in India.", hy:1},
{id:"mountbatten", n:"Lord Mountbatten", y:"Viceroy 1947", r:"Last Viceroy",
 w:"Arrived March 1947, announced the partition plan on 3 June, and advanced the transfer of power to 15 August. Stayed as India's first Governor-General until June 1948."}
],

/* --------------------------------------------------------------- movements */
movements: [
{id:"m-swadeshi", n:"Swadeshi and Boycott", from:1905, to:1908,
 lead:"Tilak, Lajpat Rai, Bipin Chandra Pal, Aurobindo Ghosh; Surendranath Banerjee in Bengal",
 cause:"The partition of Bengal, announced 19 July 1905 and effective 16 October 1905.",
 w:"Boycott of British goods and institutions, promotion of Indian manufacture, national education, and the samitis. It was the first movement to combine economic pressure with cultural symbolism, and the first in which students and women took a visible public part.",
 out:"The partition was annulled in 1911. The movement itself split the Congress at Surat in 1907 and fell away after 1908, but it set the pattern every later movement followed.", hy:1},
{id:"m-noncoop", n:"Non-Cooperation", from:1920, to:1922,
 lead:"Gandhi, with the Ali brothers on the Khilafat side",
 cause:"The Rowlatt Act, Jallianwala Bagh, and the Khilafat grievance.",
 w:"Surrender of titles and honours; boycott of legislatures, courts, schools and foreign cloth; picketing of liquor shops; national schools and panchayats in their place. Approved at Calcutta in September 1920 and endorsed at Nagpur in December.",
 out:"Withdrawn on 11 February 1922 after Chauri Chaura. It failed in its stated aim of swaraj within a year, and succeeded in making the Congress a mass organisation.", hy:1},
{id:"m-civil", n:"Civil Disobedience", from:1930, to:1934,
 lead:"Gandhi; Patel in Gujarat; Khan Abdul Ghaffar Khan in the North-West Frontier",
 cause:"The rejection of the Nehru Report's demands and the Lahore resolution for complete independence.",
 w:"Began with the Dandi March from 12 March to 6 April 1930 and the making of salt. Widened into refusal of revenue, breach of forest laws, boycott of foreign cloth and liquor, and a no-tax campaign. Suspended by the Gandhi-Irwin Pact of March 1931, resumed in 1932 after the Second Round Table Conference failed.",
 out:"Formally ended in 1934. It did not win independence, but it made the British negotiate, and it produced the Round Table Conferences, the Communal Award and the Poona Pact.", hy:1},
{id:"m-quit", n:"Quit India", from:1942, to:1944,
 lead:"Effectively leaderless — the entire Congress leadership was arrested within hours. Jayaprakash Narayan, Ram Manohar Lohia, Aruna Asaf Ali and Usha Mehta led the underground.",
 cause:"The failure of the Cripps Mission, wartime hardship, and the Japanese advance to India's eastern frontier.",
 w:"'Do or Die.' Strikes, hartals, attacks on railways, telegraphs and police stations, and parallel governments at Ballia, Tamluk in Midnapore, and Satara — which lasted until 1945. Usha Mehta ran an underground Congress Radio.",
 out:"Crushed within months, with mass arrests and firing. But it made plain that British rule could no longer be maintained by consent, and after the war no British government seriously proposed to keep India.", hy:1},
{id:"m-khilafat", n:"Khilafat", from:1919, to:1924,
 lead:"Shaukat and Muhammad Ali, Maulana Azad, Hakim Ajmal Khan, Hasrat Mohani",
 cause:"The dismemberment of the Ottoman empire and the position of the Caliph after the First World War.",
 w:"Joined to Non-Cooperation by Gandhi, against the advice of several colleagues, on the view that it was the one issue that could bring Muslims into a mass national movement.",
 out:"Ended when Ataturk abolished the Caliphate in 1924. It produced the closest Hindu-Muslim political cooperation of the whole period — and its collapse was followed by some of the worst communal rioting of the 1920s.", hy:1},
{id:"m-homerule", n:"Home Rule", from:1916, to:1918,
 lead:"Bal Gangadhar Tilak and Annie Besant, in two separate leagues",
 cause:"The First World War, the internment of leaders, and the absence of the Congress from active agitation.",
 w:"Tilak's league from Belgaum in April 1916 worked Maharashtra, Karnataka, Berar and the Central Provinces; Besant's from Madras in September 1916 worked the rest of the country. Propaganda, public meetings, and a network of local branches.",
 out:"Besant's internment in 1917 made her a national figure and forced Montagu's August 1917 declaration. The leagues faded after the 1919 Act, but they had built the organisation Gandhi inherited.", hy:1},
{id:"m-revolutionary", n:"The revolutionary movement", from:1905, to:1931,
 lead:"Anushilan Samiti and Jugantar in Bengal; the HRA and HSRA in the north; the Ghadar Party abroad",
 cause:"Impatience with constitutional methods, and the repression that followed Swadeshi.",
 w:"Alipore bomb case (1908), the Delhi Conspiracy against Hardinge (1912), the Ghadar plan of 1915, Kakori (1925), the killing of Saunders (1928), the Assembly bomb (1929), and the Chittagong armoury raid under Surya Sen (1930).",
 out:"Militarily negligible, politically considerable. The trials gave the accused a public platform, and the executions — above all Bhagat Singh's in 1931 — created a second tradition of nationalism alongside Gandhi's.", hy:1},
{id:"m-peasant", n:"Peasant and tribal risings", from:1857, to:1947,
 lead:"Varied and local",
 cause:"Revenue demands, tenancy, forest law, indigo and moneylenders.",
 w:"Indigo revolt (1859-60), Pabna (1873), Deccan riots (1875), Santhal hool (1855-56), Munda ulgulan under Birsa Munda (1899-1900), Champaran (1917), Kheda (1918), Bardoli (1928), Moplah (1921), Tebhaga (1946) and Telangana (1946-51).",
 out:"Mostly suppressed, but several forced legislation — the Bengal Tenancy Act of 1885, the Deccan Agriculturists' Relief Act of 1879 — and the later ones brought the peasantry into the national movement.", hy:1}
]

};
